don't require a work_dir if we're just restarting a stopped container, but if one is provided, error out if it's not the same as the existing one

diff --git a/initbuilder b/initbuilder
--- a/initbuilder
+++ b/initbuilder
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-# TODO if the container already exists, don't require a "work-dir" argument.
-#      if work-dir is passed anyway, error out if it doesn't match the saved work dir
-
 CONTAINER_NAME=osg-build
 IMAGE=opensciencegrid/osg-build
 MOUNT_POINT=/home/build/work
@@ -14,7 +11,7 @@ die () {
     exit 1
 }
 
-if [[ $# -ne 1 ]]; then
+usage_and_die () {
     echo "Usage: $(basename "$0") <work-dir>"
     echo
     echo "work-dir is the name of a directory above your repository checkouts."
@@ -27,18 +24,15 @@ if [[ $# -ne 1 ]]; then
     echo
     echo "The directory will be mounted under $MOUNT_POINT"
     exit 2
-fi
+}
 
 [[ -r $HOME/.globus/usercert.pem ]] || die "~/.globus/usercert.pem not found or not readable"
 [[ -r $HOME/.globus/userkey.pem ]] || die "~/.globus/userkey.pem not found or not readable"
 [[ -L $HOME/.globus/usercert.pem ]] && die "~/.globus/usercert.pem is a symlink; turn it into a regular file"
 [[ -L $HOME/.globus/userkey.pem ]] && die "~/.globus/userkey.pem is a symlink; turn it into a regular file"
 
-work_dir=${1?}  # should never actually fail
+work_dir=${1-}
 
-[[ -x $work_dir ]] || die "$work_dir not found or not readable"
-
-work_dir=$(cd "$work_dir" && pwd -P) || die "error getting absolute path of $work_dir"
 
 set -eu
 
@@ -65,9 +59,12 @@ else
 fi
 
 if $container_already_exists; then
-    echo "container \`$CONTAINER_NAME' already exists"
-    echo "Ignoring <work-dir>"
-else
+if ! $container_already_exists; then
+    if [[ ! $work_dir ]]; then
+        die_with_usage
+    fi
+    [[ -x $work_dir ]] || die "$work_dir not found or not readable"
+    work_dir=$(cd "$work_dir" && pwd -P) || die "error getting absolute path of $work_dir"
     echo -n "creating container: "
     if $rootless_podman; then
         # We're using user namespaces; we need to make sure the current user
@@ -89,6 +86,17 @@ fi
 
 $docker start $CONTAINER_NAME
 sleep 2
+
+if $container_already_exists && [[ $work_dir ]]; then  # make sure work_dir is same as inside
+    real_work_dir=$(cd "$work_dir" 2>/dev/null && pwd -P)
+    if [[ $real_work_dir ]]; then
+        existing_work_dir=$($docker exec $CONTAINER_NAME cat /home/build/.work_dir)
+        if [[ $real_work_dir != $existing_work_dir ]]; then
+            $docker stop $CONTAINER_NAME
+            die "Specified work dir $work_dir does not match work dir of existing container $existing_work_dir"
+        fi
+    fi
+fi
 
 # We mounted the grid credentials in a separate directory, so we can copy
 # them to ~build/.globus and have the permissions be correct.  Do that --
