WIP: use a certkey instead of a proxy -- bits are matyas-specific

diff --git a/initbuilder b/initbuilder
--- a/initbuilder
+++ b/initbuilder
@@ -26,10 +26,16 @@ usage_and_die () {
     exit 2
 }
 
-[[ -r $HOME/.globus/usercert.pem ]] || die "~/.globus/usercert.pem not found or not readable"
-[[ -r $HOME/.globus/userkey.pem ]] || die "~/.globus/userkey.pem not found or not readable"
-[[ -L $HOME/.globus/usercert.pem ]] && die "~/.globus/usercert.pem is a symlink; turn it into a regular file"
-[[ -L $HOME/.globus/userkey.pem ]] && die "~/.globus/userkey.pem is a symlink; turn it into a regular file"
+# FIXME duh
+mount_matyas_certkey=false
+if [[ -r /dev/shm/matyas-certkey.pem ]]; then
+    mount_matyas_certkey=true
+else
+    [[ -r $HOME/.globus/usercert.pem ]] || die "~/.globus/usercert.pem not found or not readable"
+    [[ -r $HOME/.globus/userkey.pem ]] || die "~/.globus/userkey.pem not found or not readable"
+    [[ -L $HOME/.globus/usercert.pem ]] && die "~/.globus/usercert.pem is a symlink; turn it into a regular file"
+    [[ -L $HOME/.globus/userkey.pem ]] && die "~/.globus/userkey.pem is a symlink; turn it into a regular file"
+fi
 
 work_dir=${1-}
 
@@ -75,8 +81,13 @@ if ! $container_already_exists; then
         userns_arg=
     fi
 
+    if $mount_matyas_certkey; then
+        cred_volmount="$HOME/.globus:/root/globus:ro"
+    else
+        cred_volmount="/dev/shm/matyas-certkey.pem:/dev/shm/certkey.pem:ro"
+    fi
     $docker create -it \
-                      --volume "$HOME/.globus":/root/globus:ro \
+                      --volume "$cred_volmount" \
                       --volume "$work_dir":"$MOUNT_POINT" \
                       --name $CONTAINER_NAME \
                       $userns_arg \
@@ -98,11 +109,13 @@ if $container_already_exists && [[ $work_dir ]]; then  # make sure work_dir is s
     fi
 fi
 
-# We mounted the grid credentials in a separate directory, so we can copy
-# them to ~build/.globus and have the permissions be correct.  Do that --
-# we need to be root inside.
-$docker exec -u 0 $CONTAINER_NAME  install    -m 0644 -o ${INSIDE_UID} -g ${INSIDE_GID} /root/globus/usercert.pem /home/build/.globus/usercert.pem
-$docker exec -u 0 $CONTAINER_NAME  install    -m 0600 -o ${INSIDE_UID} -g ${INSIDE_GID} /root/globus/userkey.pem /home/build/.globus/userkey.pem
+if ! $mount_matyas_certkey; then
+    # We mounted the grid credentials in a separate directory, so we can copy
+    # them to ~build/.globus and have the permissions be correct.  Do that --
+    # we need to be root inside.
+    $docker exec -u 0 $CONTAINER_NAME  install    -m 0644 -o ${INSIDE_UID} -g ${INSIDE_GID} /root/globus/usercert.pem /home/build/.globus/usercert.pem
+    $docker exec -u 0 $CONTAINER_NAME  install    -m 0600 -o ${INSIDE_UID} -g ${INSIDE_GID} /root/globus/userkey.pem /home/build/.globus/userkey.pem
+fi
 
 if ! $container_already_exists; then
     $docker exec $CONTAINER_NAME \
